#!/bin/bash

## Created By Aditya Shakya

#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 50 -hide-scrollbar -line-padding 4 -padding 10 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
case "$MENU" in
    *Lock) i3lock-fancy ;;
    *Logout) i3-msg --exit;;
    *Reboot) systemctl reboot ;;
    *Shutdown) systemctl -i poweroff
esac
