#!/bin/bash -   
#title          :date_helper.sh
#description    :print date andthe corresponding unix command
#author         :John Stilia
#date           :20200315
#version        :0.1    
#usage          :./date_helper.sh
#notes          :       
#bash_version   :5.0.16(1)-release
#============================================================================


                
# ----------------------------------
# Colors
# ----------------------------------
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

# example ${BLUE}example text${NOCOLOR}         




# An overly obvious reference for most commonly requested bash timestamps
# Now all you Mac fags can stop pestering me.

cat << EOD
        Format/result     	        |       Command              |          Output
	--------------------------------+----------------------------+------------------------------
	YYYY-MM-DD_hh:mm:ss             | date +%F_%T                | $(date +%F_%T)
	YYYYMMDD_hhmmss                 | date +%Y%m%d_%H%M%S        | $(date +%Y%m%d_%H%M%S)
	YYYYMMDD_hhmmss (UTC version)   | date --utc +%Y%m%d_%H%M%SZ | $(date --utc +%Y%m%d_%H%M%SZ)
	YYYYMMDD_hhmmss (with local TZ) | date +%Y%m%d_%H%M%S%Z      | $(date +%Y%m%d_%H%M%S%Z)
	YYYYMMSShhmmss                  | date +%Y%m%d%H%M%S         | $(date +%Y%m%d%H%M%S)
	YYYYMMSShhmmssnnnnnnnnn         | date +%Y%m%d%H%M%S%N       | $(date +%Y%m%d%H%M%S%N)
	YYMMDD_hhmmss                   | date +%y%m%d_%H%M%S        | $(date +%y%m%d_%H%M%S)
	Seconds since UNIX epoch:       | date +%s                   | $(date +%s)
	Nanoseconds only:               | date +%N                   | $(date +%N)
	Nanoseconds since UNIX epoch:   | date +%s%N                 | $(date +%s%N)
	ISO8601 UTC timestamp           | date --utc +%FT%TZ         | $(date --utc +%FT%TZ)
	ISO8601 UTC timestamp + ms      | date --utc +%FT%T.%3NZ     | $(date --utc +%FT%T.%3NZ)
	ISO8601 Local TZ timestamp      | date +%FT%T%Z              | $(date +%FT%T%Z)
	YYYY-MM-DD (Short day)          | date +%F\(%a\)             | $(date +%F\(%a\))
	YYYY-MM-DD (Long day)           | date +%F\(%A\)             | $(date +%F\(%A\))
EOD
