#!/bin/bash -
#title          :mkflask.sh
#description    :Make a backboe for a flask application
#author         :John Stilia
#date           :20200119
#version        :0.1
#usage          :./mkflask.sh
#notes          :
#bash_version   :5.0.11(1)-release
#============================================================================

# ----------------------------------
# Colors
# ----------------------------------
NOCOLOR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHTGRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
LIGHTRED='\033[1;31m'
LIGHTGREEN='\033[1;32m'
YELLOW='\033[1;33m'
LIGHTBLUE='\033[1;34m'
LIGHTPURPLE='\033[1;35m'
LIGHTCYAN='\033[1;36m'
WHITE='\033[1;37m'

# example ${BLUE}example text${NOCOLOR}

appname=$1
if [ -z $appname ]; then
  echo -e "${RED}Appname is empty.${NOCOLOR} Run me as ${BLUE}mkflask appname${NOCOLOR} "
  exit 128
fi

mkdir $appname
cd $appname

git init

virtualenv env
source env/bin/activate
touch app.py .gitignore README.md requirements.txt
pip install Flask==0.10.1
pip freeze >requirements.txt

echo -e "#!/usr/bin/env python

from flask import Flask
app = Flask(__name__)


@app.route('/')
def hello():
	return "Hello World!"

if __name__ == '__main__':
	app.run()
" >./app.py

git add .
git commit -am ' init commit'
